services:
  peer1:
    image: netapp
    networks:
      - p2pnetwork
    environment:
      - PEER_PORT=8001
  peer2:
    image: netapp
    networks:
      - p2pnetwork
    environment:
      - PEER_PORT=8002

networks:
  p2pnetwork:
    driver: bridge